# Generated by Django 3.0.6 on 2020-06-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('body_content', models.TextField(verbose_name='Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Campos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('template_content', models.CharField(max_length=255, verbose_name='Contenido')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_templates.Plantilla', verbose_name='Plantilla')),
            ],
        ),
    ]
