# Generated by Django 3.2.4 on 2021-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('body_content', models.TextField(verbose_name='Contenido')),
            ],
        ),
    ]
