# Generated by Django 3.0.6 on 2020-06-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campos',
            new_name='Campo',
        ),
    ]
