# Generated by Django 3.0.6 on 2020-06-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_templates', '0002_auto_20200627_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='plantilla',
        ),
    ]
