# Generated by Django 3.0.6 on 2020-06-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_templates', '0003_remove_campo_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='asunto',
            field=models.CharField(default='Desde el gabinete de presidencia, feliz navidad!', max_length=255, verbose_name='Asunto'),
            preserve_default=False,
        ),
    ]
