# Generated by Django 3.0.6 on 2020-06-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_templates', '0004_plantilla_asunto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campo',
        ),
    ]
