image: python:3.8.10

services:
  - mysql:latest

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - apt-get update && apt-get -y install libsasl2-dev python-dev libldap2-dev libssl-dev
  - python -V  # Print out python version for debugging
  - pip install -r requirements.txt

test:
  script:
    - python manage.py test
  tags:
    - runner-docker
