image: python:3.8.10

variables:
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  TESTING: "true"

stages:
  - linter
  - test

services:
  - name: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]

cache:
  paths:
    - $CI_PROJECT_DIR/.cache/pip

before_script:
  - apt-get update && apt-get -y install libsasl2-dev python-dev libldap2-dev libssl-dev
  - python -V  # Print out python version for debugging
  - pip install -r requirements.txt

test:
  script:
    - cd contactosapi && python manage.py test
  tags:
    - python
    - tests

flake8:
  stage: linter
  script:
    - flake8 --max-line-length=120 contactosapi/*.py
  tags:
    - python
    - tests

flake8:
  stage: linter
  allow_failure: true
  script:
    - pylint -d C0301 contactosapi/*.py
  tags:
    - python
    - tests


