# Generated by Django 3.0.6 on 2020-06-01 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('agenda', '0001_initial'), ('agenda', '0002_auto_20200529_0925'), ('agenda', '0003_auto_20200529_0925'), ('agenda', '0004_cargo_persona'), ('agenda', '0005_auto_20200601_1022')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Colectivos',
                'db_table': 'colectivos',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'db_table': 'países',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tratamientos',
            },
        ),
        migrations.CreateModel(
            name='SubColectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('colectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Colectivo')),
            ],
            options={
                'verbose_name_plural': 'SubColectivos',
                'db_table': 'subcolectivos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=500, verbose_name='Apellidos')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.Tratamiento')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
                'unique_together': {('nombre', 'apellidos')},
            },
        ),
        migrations.AlterModelTable(
            name='pais',
            table='paises',
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=500, verbose_name='Cargo')),
                ('finalizado', models.BooleanField()),
                ('ciudad', models.CharField(max_length=500, verbose_name='Ciudad')),
                ('cod_postal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('empresa', models.CharField(max_length=500, verbose_name='Empresa')),
                ('fecha_cese', models.DateField(blank=True, verbose_name='Fecha finalización del cargo')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(null=True)),
                ('colectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.Colectivo')),
                ('subcolectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.SubColectivo')),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pais', models.ForeignKey(default=65, on_delete=django.db.models.deletion.PROTECT, to='agenda.Pais', verbose_name='Pais')),
                ('provincia', models.ForeignKey(default=45, on_delete=django.db.models.deletion.PROTECT, to='agenda.Provincia', verbose_name='Provincia')),
                ('persona', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.Persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
            },
        ),
    ]
