# Generated by Django 3.2.4 on 2021-08-24 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=500, verbose_name='Cargo')),
                ('finalizado', models.BooleanField()),
                ('ciudad', models.CharField(blank=True, max_length=500, verbose_name='Ciudad')),
                ('cod_postal', models.CharField(blank=True, max_length=5, verbose_name='Código Postal')),
                ('direccion', models.CharField(blank=True, max_length=500, verbose_name='Dirección')),
                ('empresa', models.CharField(max_length=500, verbose_name='Empresa')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='Fecha finalización del cargo')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('unique_key', models.CharField(max_length=255, unique=True, verbose_name='Unique key')),
            ],
            options={
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Colectivos',
                'db_table': 'colectivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'db_table': 'paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tratamientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('numero', models.CharField(max_length=255, verbose_name='Número de telf.')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='agenda.cargo')),
            ],
            options={
                'verbose_name_plural': 'Teléfonos',
                'db_table': 'telefonos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubColectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('unique_key', models.CharField(max_length=255, unique=True, verbose_name='Unique key')),
                ('colectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcolectivos', to='agenda.colectivo')),
            ],
            options={
                'verbose_name_plural': 'SubColectivos',
                'db_table': 'subcolectivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=500, null=True, verbose_name='Apellidos')),
                ('unique_key', models.CharField(max_length=255, unique=True, verbose_name='Unique key')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.tratamiento')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OtroContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('dato', models.CharField(max_length=255, verbose_name='Dato de contacto')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.cargo')),
            ],
            options={
                'verbose_name': 'Otro contacto',
                'verbose_name_plural': 'Otros contactos',
                'db_table': 'otros_contactos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='agenda.cargo')),
            ],
            options={
                'verbose_name_plural': 'Correos',
                'db_table': 'correos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.colectivo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.pais', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='agenda.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='subcolectivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.subcolectivo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='usuario_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
