# Generated by Django 3.0.6 on 2020-06-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_squashed_0005_auto_20200601_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.Pais', verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.Provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subcolectivo',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='subcolectivo',
            unique_together={('nombre', 'colectivo')},
        ),
    ]
