# Generated by Django 3.0.6 on 2020-06-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20200601_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=500, null=True, verbose_name='Apellidos'),
        ),
    ]
