# Generated by Django 3.0.6 on 2020-06-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20200601_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fecha_cese',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha finalización del cargo'),
        ),
    ]
