# Generated by Django 3.0.6 on 2020-05-29 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20200529_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.Persona', verbose_name='Persona'),
            preserve_default=False,
        ),
    ]
