# Generated by Django 3.0.6 on 2020-06-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_cargo_persona'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('nombre', 'apellidos')},
        ),
    ]
