# Generated by Django 3.0.6 on 2020-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_correo_otrocontacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='nota',
            field=models.CharField(max_length=255, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='otrocontacto',
            name='nota',
            field=models.CharField(max_length=255, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='nota',
            field=models.CharField(max_length=255, null=True, verbose_name='Nota'),
        ),
    ]
