# Generated by Django 3.0.6 on 2020-06-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20200602_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['-fecha_alta'], 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='colectivo',
            options={'ordering': ['id'], 'verbose_name_plural': 'Colectivos'},
        ),
        migrations.AlterModelOptions(
            name='correo',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Correos'},
        ),
        migrations.AlterModelOptions(
            name='otrocontacto',
            options={'ordering': ['nombre'], 'verbose_name': 'Otro contacto', 'verbose_name_plural': 'Otros contactos'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellidos', 'nombre'], 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='subcolectivo',
            options={'ordering': ['id'], 'verbose_name_plural': 'SubColectivos'},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Teléfonos'},
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='agenda.Persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='agenda.Cargo'),
        ),
        migrations.AlterField(
            model_name='subcolectivo',
            name='colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcolectivos', to='agenda.Colectivo'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='agenda.Cargo'),
        ),
    ]
