# Generated by Django 3.0.6 on 2020-06-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20200617_1407'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('cargo', 'persona', 'empresa')},
        ),
    ]
