# Generated by Django 3.0.6 on 2020-06-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20200625_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='subcolectivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.SubColectivo'),
        ),
    ]
