# Generated by Django 3.0.6 on 2020-07-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20200630_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='ciudad',
            field=models.CharField(max_length=500, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cod_postal',
            field=models.CharField(max_length=5, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='direccion',
            field=models.CharField(max_length=500, null=True, verbose_name='Dirección'),
        ),
    ]
