# Generated by Django 3.0.6 on 2020-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_auto_20200707_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=5, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
