# Generated by Django 3.2.4 on 2021-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('contactos', models.ManyToManyField(blank=True, to='agenda.Cargo')),
            ],
            options={
                'verbose_name_plural': 'Listas',
                'db_table': 'listas',
                'ordering': ['id'],
            },
        ),
    ]
