# Generated by Django 3.0.6 on 2020-06-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='descripcion',
            field=models.CharField(default='Lista para felicitar las Navidades del 2020', max_length=255, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
