# Generated by Django 3.0.6 on 2020-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20200625_1917'),
        ('listas', '0002_lista_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='contactos',
            field=models.ManyToManyField(blank=True, to='agenda.Cargo'),
        ),
    ]
